[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Note: For production deployment, you'll need to set up a hosted Ollama instance
  # or modify the code to use a cloud-based API service

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
