// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdksgbnkuddysqwqnczk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNka3NnYm5rdWRkeXNxd3FuY3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMDA2MTgsImV4cCI6MjA1NzU3NjYxOH0.xiA9Vr3IsHuJMOBuWQQl9dTJKlKtA80E7QzcnM_cws8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);